# Generated by Django 3.2.16 on 2023-02-05 17:36

from django.db import migrations, models
import django.db.models.deletion
import src.apps.common.file_renamer


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.apps.common.file_renamer.PathAndRename('products')),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
